complexity:
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 30
    thresholdInInterfaces: 30
    thresholdInObjects: 30
    thresholdInEnums: 30
naming:
  ConstructorParameterNaming:
    excludeClassPattern: 'TestEnvironmentProperties'
exceptions:
  TooGenericExceptionThrown:
    active: false
  SwallowedException:
    active: false

